steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', ' gcr.io/gcp-rain/github.com/jeeeevs/express:maste', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', ' gcr.io/gcp-rain/github.com/jeeeevs/express:maste']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/my-deployment', 'my-container= gcr.io/gcp-rain/github.com/jeeeevs/express:maste']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=terraform-gke-cluster'
images:
- ' gcr.io/gcp-rain/github.com/jeeeevs/express:maste'

# cloud build